### ISSUE TITLE
Set hardening headers

### ISSUE THREAD

**Issue by adityasaky** [theupdateframework/theupdateframework.io#11]
For TUF to complete the requirements using https://theupdateframework.io/ for the CII Best Practices Gold badge, it must include certain hardening headers. They are:
- Content Security Policy (CSP)
- HTTP Strict Transport Security (already set)
- X-Content-Type-Options (as "nosniff")
- X-Frame-Options

I'm looking at the headers using https://securityheaders.com/?q=https%3A%2F%2Ftheupdateframework.io&followRedirects=on and the requirements for the gold badge criteria can be found at https://bestpractices.coreinfrastructure.org/en/projects/1351?criteria_level=2#hardened_site.

**Comment by lukpueh** [comment]
Fixed in #32
