### ISSUE TITLE
History page abruptly cut?

### ISSUE THREAD

**Issue by perjahn** [theupdateframework/theupdateframework.io#113]
The text in the history page appear to be abruptly cut in the middle of a sentence.
https://github.com/theupdateframework/theupdateframework.io/blob/main/content/en/docs/project/history.md

**Comment by JustinCappos** [comment]
@chalin Do we have a copy of the old text here?   It looks like it may have been cut off when we switched styles?

**Comment by chalin** [comment]
Yes, the state of the repo before the LFX work is here: https://github.com/theupdateframework/theupdateframework.io/tree/pre-lfx-2024.

This is the page link: https://github.com/theupdateframework/theupdateframework.io/blob/pre-lfx-2024/content/history.md

I'll get to adding the missing text soon.
