### ISSUE TITLE
Have a list with some of the most notable TUF implementations

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/theupdateframework.io#27]
Currently, some of the hyperlinks in the website refer mostly to the [python-tuf](https://github.com/theupdateframework/python-tuf) reference implementation, but maybe it would be nice to mention some of the other most notable implementations as well.

So far the website lists:

- [dtuf](https://github.com/davedoesdev/dtuf)
- [rust-tuf](https://github.com/heartsucker/rust-tuf)

under [main/adoptions/other](https://theupdateframework.com/adoptions/), but there are others like php-tuf, go-tuf, tough, etc.

**Comment by udf2457** [comment]
awslabs/tough library and the associated `tuftool` CLI tool.

**Comment by joshuagl** [comment]
It would be great to move out the implementations to a separate page, i.e. Getting started -> Implementations, and list the implementations we know of. 

Marina & Justin's maintainer track talk at KubeCon NA in Detroit included a list of known implementations, we could use that list as a starting point.

**Comment by joshuagl** [comment]
Thanks @h4l0gen, I agree we can close this issue thanks to the [Implementations](https://theupdateframework.io/implementations/) page introduced in #47
