### ISSUE TITLE
Outdated link to maybe outdated whitepaper

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/theupdateframework.io#30]
On the overview page we [reference `Secunia_RSA_Software_Portfolio_Security_Exposure.pdf`](https://github.com/theupdateframework/theupdateframework.io/blame/master/content/overview.md#L10-L11) to support the claim that "*an average Windows user probably contains about two dozen different software updaters"*.

The link does not resolve to the corresponding paper anymore, and [a paper that I found under this name](https://techzoom.net/static/whitepapers/software_portfolio_security_exposure_2010.pdf) is from 2010 (I wonder if the claim is still true in 2022?)

Let's either update the link or remove it altogether.

**Comment by lukpueh** [comment]
Yeah, let's remove the whole sentence. (The one in parentheses)

**Comment by h4l0gen** [comment]
Okay i will make change.
