### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [theupdateframework/theupdateframework.io#42]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

**Comment by joshuagl** [comment]
Thanks for reporting. I don't have permissions to view that page and AFAICT the build image isn't controlled by configuration in this repository. Are you able to help?

**Comment by nate-double-u** [comment]
@joshuagl as you're a maintainer I'm able to invite you to the Netlify team -- if this is appropriate, let me know which email address you'd like me to use (either here, or in the CNCF slack)

**Comment by nate-double-u** [comment]
Thanks @joshuagl, invite sent.

**Comment by joshuagl** [comment]
Thanks @nate-double-u. I followed the steps [here](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239) and everything seems OK! 👍
