### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by chalin** [theupdateframework/theupdateframework.io#64]
This is following most other CNCF repos. For details see:

- [Renaming the default branch from master](https://github.com/github/renaming?tab=readme-ov-file#renaming-the-default-branch-from-master)
- https://inclusivenaming.org
- [Cloud Native Computing Foundation’s Inclusive Naming Initiative](https://www.cncf.io/announcements/2021/05/04/cloud-native-computing-foundations-inclusive-naming-initiative-selected-as-honorable-mention-in-the-software-category-of-fast-companys-2021-world-changing-ideas-awards/)

We've done so recently for in-toto:

- https://github.com/in-toto/in-toto.io/issues/42

@lukpueh - I'm glad to handle the rename here too if you give a thumbs up.

**Comment by lukpueh** [comment]
> @lukpueh - I'm glad to handle the rename here too if you give a thumbs up.

Appreciated!

**Comment by chalin** [comment]
Done. Note to all: you'll need to update your local fork if you have one. For details:

> <img width="502" alt="image" src="https://github.com/user-attachments/assets/4a62f0e9-d281-4d82-8394-050429315196">

**Comment by chalin** [comment]
Confirming that the builds work over `main`, see https://app.netlify.com/sites/theupdateframework/deploys/66d79a30a7edd4df6d70d7e4:

> <img width="288" alt="image" src="https://github.com/user-attachments/assets/e4e1f47b-1832-4983-bd72-873ab0c6283a">
