### ISSUE TITLE
[docsy] Post-LFX T2 mentorship site work

### ISSUE THREAD

**Issue by chalin** [theupdateframework/theupdateframework.io#85]
- [x] Ensure grant info appears on the site and in footer:
  - [x] #86
  - [x] #89
- [x] Ensure base specs page path is `/specs` rather than `/specifications/specs` - #88
- [x] #82
- [x] #93
- [x] #94
- [x] #101
- [x] #104
- [ ] #91
  - [x] #92
  - [ ] ...
- [x] **Pre-LFX website**: create a branch, and enable branch deploys over it, so we can view the pre-LFX version. Done:
    https://pre-lfx-2024--theupdateframework.netlify.app
- [x] Remove `docsy` from the branch deploy list
- [x] Submit PR from [docsy](https://github.com/theupdateframework/theupdateframework.io/tree/docsy) branch - #105
- [ ] Drop the `github_branch` setting, so that we fall back to `main`

**Resources**:

- _Pre-LFX website_ version: https://pre-lfx-2024--theupdateframework.netlify.app

**Comment by Jason-123-cyber** [comment]
> * * [x]  Ensure grant info appears on the site and in footer:
>     
>     * [x]  [[docsy] Add About page to hold project and grant info #86](https://github.com/theupdateframework/theupdateframework.io/pull/86)* [x]  [[docsy] About section rework: add headers #89](https://github.com/theupdateframework/theupdateframework.io/pull/89)[x]  Ensure base specs page path is `/specs` rather than `/specifications/specs` - [[docsy] Reworked Spec page, including wildcard redirects #88](https://github.com/theupdateframework/theupdateframework.io/pull/88)[x]  [Add support for external link checking #82](https://github.com/theupdateframework/theupdateframework.io/issues/82)[x]  [[docsy] New IA #93](https://github.com/theupdateframework/theupdateframework.io/issues/93)[x]  [[docsy] Recover security audits page #94](https://github.com/theupdateframework/theupdateframework.io/issues/94)[x]  [[docsy] Adjust links to spec, community contrib page, repo src #101](https://github.com/theupdateframework/theupdateframework.io/pull/101)[x]  [[docsy] Spec page: make link to latest a button, tweak external link rules #104](https://github.com/theupdateframework/theupdateframework.io/pull/104)* [ ]  [[docsy] Enable site search #91](https://github.com/theupdateframework/theupdateframework.io/issues/91) --> will be worked on later
>     
>     * [x]  [[docsy] Configure Google Custom Search Engine but leave it disabled #92](https://github.com/theupdateframework/theupdateframework.io/pull/92)[x]  **Pre-LFX website**: create a branch, and enable branch deploys over it, so we can view the pre-LFX version. Done:
>   https://pre-lfx-2024--theupdateframework.netlify.app[x]  Remove `docsy` from the branch deploy list[x]  Submit PR from [docsy](https://github.com/theupdateframework/theupdateframework.io/tree/docsy) branch - [New and improved Docsy-based version of the website  #105](https://github.com/theupdateframework/theupdateframework.io/pull/105)[x]  Drop the `github_branch` setting, so that we fall back to `main` - [Adjustments for page-meta links #106](https://github.com/theupdateframework/theupdateframework.io/pull/106)
> 
> **Resources**:
> 
> * _Pre-LFX website_ version: https://pre-lfx-2024--theupdateframework.netlify.app
> * [@lukpueh](https://github.com/lukpueh)'s main comments about an earlier version of the Docsy-based version of the website: [Feedback on Docs and community sections on Docsy theme Dindihub/docsy-tuf.io#1 (review)](https://github.com/Dindihub/docsy-tuf.io/pull/1#pullrequestreview-2201331499)
